export const types = {
  CURRENT_AUTHENTICATED_USER_REQUEST: 'CURRENT_AUTHENTICATED_USER_REQUEST',
  CURRENT_AUTHENTICATED_USER_SUCCESS: 'CURRENT_AUTHENTICATED_USER_SUCCESS',
  CURRENT_AUTHENTICATED_USER_FAILURE: 'CURRENT_AUTHENTICATED_USER_FAILURE',

  CURRENT_USER_POOL_REQUEST: 'CURRENT_USER_POOL_REQUEST',
  CURRENT_USER_POOL_SUCCESS: 'CURRENT_USER_POOL_SUCCESS',
  CURRENT_USER_POOL_FAILURE: 'CURRENT_USER_POOL_FAILURE',

  SIGN_IN_USER_REQUEST: 'SIGN_IN_USER_REQUEST',
  SIGN_IN_USER_SUCCESS: 'SIGN_IN_USER_SUCCESS',
  SIGN_IN_USER_FAILURE: 'SIGN_IN_USER_FAILURE',

  SIGN_IN_NEW_PASSWORD_REQUIRED: 'SIGN_IN_NEW_PASSWORD_REQUIRED',

  SIGN_IN_RESET_PASSWORD_REQUEST: 'SIGN_IN_RESET_PASSWORD_REQUEST',
  SIGN_IN_RESET_PASSWORD_SUCCESS: 'SIGN_IN_RESET_PASSWORD_SUCCESS',
  SIGN_IN_RESET_PASSWORD_FAILURE: 'SIGN_IN_RESET_PASSWORD_FAILURE',

  LOGOUT_USER_REQUEST: 'LOGOUT_USER_REQUEST',
  LOGOUT_USER_SUCCESS: 'LOGOUT_USER_SUCCESS',
  LOGOUT_USER_FAILURE: 'LOGOUT_USER_FAILURE',

  FORGOT_PASSWORD_REQUEST: 'FORGOT_PASSWORD_REQUEST',
  FORGOT_PASSWORD_SUCCESS: 'FORGOT_PASSWORD_SUCCESS',
  FORGOT_PASSWORD_FAILURE: 'FORGOT_PASSWORD_FAILURE',

  FORGOT_PASSWORD_SUBMIT_REQUEST: 'FORGOT_PASSWORD_SUBMIT_REQUEST',
  FORGOT_PASSWORD_SUBMIT_SUCCESS: 'FORGOT_PASSWORD_SUBMIT_SUCCESS',
  FORGOT_PASSWORD_SUBMIT_FAILURE: 'FORGOT_PASSWORD_SUBMIT_FAILURE',

  CHANGE_PASSWORD_REQUEST: 'CHANGE_PASSWORD_REQUEST',
  CHANGE_PASSWORD_FAILURE: 'CHANGE_PASSWORD_FAILURE',
  CHANGE_PASSWORD_SUCCESS: 'CHANGE_PASSWORD_SUCCESS',

  RESET_PASSWORD_REQUEST: 'RESET_PASSWORD_REQUEST',
  RESET_PASSWORD_SUCCESS: 'RESET_PASSWORD_SUCCESS',
  RESET_PASSWORD_FAILURE: 'RESET_PASSWORD_FAILURE',

  REDIRECT_REQUEST: 'REDIRECT_REQUEST',
  CLEAN_REDIRECT_REQUEST: 'CLEAN_REDIRECT_REQUEST',
  ON_CHANGE_FORM: 'ON_CHANGE_FORM',
  VERIFICATION_CODE_INPUTED: 'VERIFICATION_CODE_INPUTED'
};
