export const CREATE_GROUP = 'CREATE_GROUP'
export const UPDATE_GROUP = 'UPDATE_GROUP'
export const GET_GROUPS = 'GET_GROUPS'
export const GET_GROUP = 'GET_GROUP'
export const DELETE_GROUP = 'DELETE_GROUP'

export const CREATE_CATEGORY = 'CREATE_CATEGORY'
export const UPDATE_CATEGORY = 'UPDATE_CATEGORY'
export const GET_CATEGORIES = 'GET_CATEGORIES'
export const GET_CATEGORY = 'GET_CATEGORY'
export const DELETE_CATEGORY = 'DELETE_CATEGORY'

export const CREATE_PRODUCT = 'CREATE_PRODUCT'
export const UPDATE_PRODUCT = 'UPDATE_PRODUCT'
export const GET_PRODUCTS = 'GET_PRODUCTS'
export const DELETE_PRODUCT = 'DELETE_PRODUCT'

export const GET_COINS = 'GET_COINS'
export const UPDATE_COIN = 'UPDATE_COIN'

export const GET_SUBSCRIPTIONS_PRICING = 'GET_SUBSCRIPTIONS_PRICING'
export const UPDATE_SUBSCRIPTION_PRICE = 'UPDATE_SUBSCRIPTION_PRICE'

export const CREATE_EXERCISE = 'CREATE_EXERCISE'
export const UPDATE_EXERCISE = 'UPDATE_EXERCISE'
export const GET_EXERCISES = 'GET_EXERCISES'
export const GET_EXERCISE = 'GET_EXERCISE'
export const DELETE_EXERCISE = 'DELETE_EXERCISE'

export const CREATE_POST = 'CREATE_POST'
export const UPDATE_POST = 'UPDATE_POST'
export const GET_POSTS = 'GET_POSTS'
export const GET_POST = 'GET_POST'
